services:
  frontend:
    image: observadordedominios-frontend:latest
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    image: observadordedominios-backend:latest
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8005:8000"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: overlay
